//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NaoConformidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NaoConformidade()
        {
            this.Tbl_NaoConformidade_x_Norma = new HashSet<Tbl_NaoConformidade_x_Norma>();
        }
    
        public long IdNaoConformidade { get; set; }
        public Nullable<long> IdProcesso { get; set; }
        public Nullable<long> IdAtividadeDiaria { get; set; }
        public string DsNaoConformidade { get; set; }
        public bool Dstatus { get; set; }
        public Nullable<System.DateTime> Dt_Cadastro { get; set; }
        public Nullable<System.DateTime> Dt_Alteracao { get; set; }
    
        public virtual Tbl_Atividade_Diaria Tbl_Atividade_Diaria { get; set; }
        public virtual tbl_Processo tbl_Processo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_NaoConformidade_x_Norma> Tbl_NaoConformidade_x_Norma { get; set; }
        public long IdSequencial { get; set; }
    }
}
