//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NaoConformidade_x_Norma
    {
        public long IdNorma { get; set; }
        public long IdNaoConformidade { get; set; }
        public string UrlNorma { get; set; }
        public string Titulo { get; set; }
        public long IdSequencial { get; set; }
    
        public virtual tbl_NaoConformidade tbl_NaoConformidade { get; set; }
    }
}
